version: "3"

services:
  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - ./db-sql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: edi
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer2:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
